name: VarLight
version: "plugin.version"
author: shawlaf
main: me.shawlaf.varlight.spigot.VarLightPlugin
description: Turn Normal Blocks into Light Sources!
api-version: "api.version"

softdepend:
  - "Multiverse-Core"
  - "LightAPI"

permissions:
  varlight.admin.save:
    description: "Provides access to /varlight save and /varlight autosave"
    default: op
  varlight.admin.debug:
    description: "Provides access to /varlight debug"
    default: op
  varlight.admin.migrate:
    description: "Provides access to /varlight migrate"
    default: op
  varlight.admin.perm:
    description: "Provides access to /varlight perm"
    default: op
  varlight.admin.reload:
    description: "Provides access to /varlight reload"
    default: op
  varlight.admin.world:
    description: "Provides access to /varlight blacklist and /varlight whitelist"
    default: op
  varlight.admin.fill:
    description: "Provides access to /varlight fill and /varlight update"
    default: op
    children:
      varlight.admin.update: true
  varlight.admin.update:
    description: "Provides access to /varlight update"
    default: op
  varlight.admin.item:
    description: "Provides access to /varlight item"
    default: op
  varlight.admin.give:
    description: "Provides access to /varlight give"
    default: op
  varlight.stepsize:
    description: "Provides access to /varlight stepsize"
    default: op
  varlight.admin:
    description: "Provides access to all varlight admin commands"
    default: op
    children:
      varlight.admin.save: true
      varlight.admin.debug: true
      varlight.admin.migrate: true
      varlight.admin.perm: true
      varlight.admin.reload: true
      varlight.admin.world: true
      varlight.admin.update: true
      varlight.admin.fill: true
      varlight.admin.item: true
      varlight.admin.give: true
      varlight.stepsize: true