name: VarLight
version: "plugin.version"
author: shawlaf
main: me.shawlaf.varlight.spigot.VarLightPlugin
description: Turn Normal Blocks into Light Sources!
api-version: "1.15"
load: STARTUP

softdepend:
  - "Multiverse-Core"
  - "LightAPI"
  - "WorldEdit"
  - "WorldGuard"

permissions:
  varlight.admin.config:
    description: "Provides access to /varlight config"
    default: op
  varlight.admin.save:
    description: "Provides access to /varlight save and /varlight autosave"
    default: op
  varlight.admin.debug:
    description: "Provides access to /varlight debug"
    default: op
  varlight.admin.fill:
    description: "Provides access to /varlight fill and /varlight update"
    default: op
    children:
      varlight.admin.update: true
  varlight.admin.update:
    description: "Provides access to /varlight update"
    default: op
  varlight.admin.give:
    description: "Provides access to /varlight give"
    default: op
  varlight.admin.clear:
    desciption: "Provides access to /varlight clear"
    default: op
  varlight.stepsize:
    description: "Provides access to /varlight stepsize"
    default: op
  varlight.admin:
    description: "Provides access to all varlight admin commands"
    default: op
    children:
      varlight.admin.config: true
      varlight.admin.save: true
      varlight.admin.debug: true
      varlight.admin.world: true
      varlight.admin.update: true
      varlight.admin.fill: true
      varlight.admin.give: true
      varlight.admin.clear: true
      varlight.stepsize: true